stages:
  - build
  - deploy
Build:
  stage: build
  script:
    - docker -v
    - dapp dimg build --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}
    - dapp dimg push --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE} --tag-ci registry.devpayever.com --registry-username payever --registry-password vMnPdItXkV9T

  tags:
    - deploy
Deploy:
  stage: deploy 
  script:
  - dapp --version
  - dapp kube deploy
      --tag-ci
      --namespace default
      --set "global.env=stage"
      --set "global.git_rev=${CI_BUILD_REF:-$CI_COMMIT_SHA}"
      --set global.ciProjectName=$CI_PROJECT_NAME
      registry.devpayever.com
  tags:
    - deploy
