stages:
  - build to dev
  - deploy to dev
  - testing
  - build staging
  - deploy staging
  - manual build production
  - manual product deploy
  - post build test

Build to dev:
  stage: build to dev
  script:
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
    - sed -i -- "s/coupons-frontend/coupons-frontend-dev/g" ./.helm/Chart.yaml
    - dapp dimg build --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}
    - dapp dimg push --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}  registry.devpayever.com --registry-username payever --registry-password vMnPdItXkV9T
  tags:
    - deploy
  only:
    - branches
  except:
    - master

Deploy to dev:
  stage: deploy to dev
  script:
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
  - sed -i -- "s/coupons-frontend/coupons-frontend-dev/g" ./.helm/Chart.yaml
  - sed -i -- "s/placeholder/coupons-frontend-dev/g" ./sub.sh
  - bash sub.sh
  - dapp --version
  - dapp kube deploy
      --name coupons-frontend
      --namespace developers
      --set "global.env=stage"
      --set "global.git_rev=${CI_BUILD_REF:-$CI_COMMIT_SHA}"
      --set global.ciProjectName=$CI_PROJECT_NAME
      registry.devpayever.com
  tags:
    - deploy
  only:
    - branches
  except:
    - master

test unit:
  when: manual
  stage: testing
  tags: [deploy]
  script:
   - echo "test unit"
   - echo $CI_JOB_STAGE
   - docker build -f Dockerfile.test .
  only:
    - branches
  except:
    - master
  
test integration:
  when: manual
  stage: testing
  tags: [deploy]
  script:
   - docker build -f Dockerfile.e2e .
   - echo "test integration"
  only:
    - branches
  except:
    - master
    
Build to staging:
  stage: build staging
  when: manual
  script:
    - bash sub_stage.sh
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
    - sed -i "s/developers/staging/g" ./.helm/templates/01-backend.yaml
    - sed -i "s/developers/staging/g" ./.helm/templates/02-backend-ingress.yaml
    - sed -i "s/.devpayever.com/.payever.org/g" ./.helm/templates/02-backend-ingress.yaml
    - dapp dimg build --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}
    - dapp dimg push --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}  registry.devpayever.com --registry-username payever --registry-password vMnPdItXkV9T
  tags:
    - deploy
  only:
    - branches
  except:
    - master
  
Deploy to staging:
  stage: deploy staging
  when: manual
  script:
  - dapp --version
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
  - dapp kube deploy
      --name coupons-frontend
      --namespace staging
      --set "global.env=stage"
      --set "global.git_rev=${CI_BUILD_REF:-$CI_COMMIT_SHA}"
      --set global.ciProjectName=$CI_PROJECT_NAME
      registry.devpayever.com
  tags:
    - deploy
  only:
    - branches
  except:
    - master
    
Build to prod:  
  stage: manual build production
  when: manual
  script:
    - bash sub_prod.sh
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
    - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
    - sed -i "s/developers/production/g" ./.helm/templates/01-backend.yaml
    - sed -i "s/developers/production/g" ./.helm/templates/02-backend-ingress.yaml
    - sed -i "s/.devpayever.com/.payever.org/g" ./.helm/templates/02-backend-ingress.yaml
    - sed -i "s/custom-tls-cert-com/custom-tls-cert-org/g" ./.helm/templates/02-backend-ingress.yaml
    - dapp dimg build --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}
    - dapp dimg push --name coupons-frontend --build-dir ~/dapp_build/${CI_PROJECT_NAME} ${CI_REGISTRY_IMAGE}  registry.devpayever.com --registry-username payever --registry-password vMnPdItXkV9T
  tags:
    - deploy
  only:
    - master
    
.staging-deploy: &staging-deploy
  tags: [deploy]
  only:
    - master
  stage: manual product deploy
  when: manual
  script:
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./Dappfile
  - sed -i -- "s/coupons-frontend/$CI_COMMIT_REF_SLUG/g" ./.helm/templates/01-backend.yaml
  - sed -i "s/developers/production/g" ./.helm/templates/01-backend.yaml
  - sed -i "s/developers/production/g" ./.helm/templates/02-backend-ingress.yaml
  - sed -i "s/.devpayever.com/.payever.org/g" ./.helm/templates/02-backend-ingress.yaml
  - sed -i "s/custom-tls-cert-com/custom-tls-cert-org/g" ./.helm/templates/02-backend-ingress.yaml
  - dapp --version
  - dapp kube deploy
      --namespace production
      --set "global.env=stage"
      --set "global.git_rev=${CI_BUILD_REF:-$CI_COMMIT_SHA}"
      --set global.ciProjectName=$CI_PROJECT_NAME
      registry.devpayever.com
deploy to prod:
  <<: *staging-deploy

post build test:
  when: manual
  stage: post build test
  tags:
    - deploy
  script:
   - docker rmi $(docker images -q)
